name: CI
on: push
env:
  CI: true
  COVERAGE: true
  RAILS_ENV: test

jobs:

  #
  ## RUBOCOP
  #
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby 3.1.2
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1.2

      - name: Run Rubocop
        run: |
          bin/rubocop
